export const baseURL = process.env.VUE_APP_BASE_URL || '/myworld'
export const MY_MSG_TYPES = 'me'
export const GPT_MSG_TYPES = 'gpt'
export const ERROR_CHAT_RESP = 'bad result! ~~ dT-Tb ~~'
export const BEI_AN = '© 2023 enen - ICP备案号: <a href="https://beian.miit.gov.cn">粤ICP备2023147367号 - 1</a>'
